version: "3.9"

services:

    server:
        container_name: test_typescript-react-context_server_1
        image: ovc/test-marty:latest
        build: .
        ports:
            - "3000:3000"
        command: "yarn start"
